# Welcome to Jekyll!

# Website settings
title: Cristian Castellari
description: Il sito personale di Cristian Castellari
keywords: cristian,castellari,blog,jekyll,gh-pages
baseurl:  '' # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://skyflash.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Cristian Castellari  # Be used at blog posts' author.
  first_name: Cristian  # Be used at index page about me section.
  last_name: Castellari  # Be used at index page about me section.
  avatar: /static/assets/img/landing/me.jpg  # upload your avatar at directory and edit it.
  github_username: skyflash  # Leave blank if you don't have now
  linkedin_id: cristiancastellari # Leave blank if you don't have now
  facebook_username: cristian.castellari  # Leave blank if you don't have now
  twitter_username: BloggerStanco  # Leave blank if you don't have now
  email: c.castellari@gmail.com  # Leave blank if you don't have now
  cv: https://cv.cristiancastellari.it  # An online CV can be printed as PDF, leave blank if you don't have now
  
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-wordpress
    - name: fa-linux
  skill_icon2:
    - name: fa-apple
    - name: fa-chrome
  desc: Introduce myself will be here.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: Skyflash

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
#  id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# Jekyll-SEO-tag settings
lang: it_IT
permalink: pretty
## Codici di verifica
webmaster_verifications:
#  google:

plugins:
  - jekyll-seo-tag

# scss
sass:
  sass_dir: _sass
  style: compressed

# Build settings
encoding: utf-8

jekyll_admin:
  hidden_links:
#    - posts
#    - pages
#    - staticfiles
#    - datafiles
#    - configuration

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
